package edsdk.bindings;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import edsdk.bindings.EdSdkLibrary.EdsStreamRef;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : D:\ims_archive\C++\SDK\ED-SDK\Ver215\EDSDK\Header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagEdsSaveImageSetting extends Structure {
	/** C type : EdsUInt32 */
	public NativeLong JPEGQuality;
	/** C type : EdsStreamRef */
	public EdsStreamRef iccProfileStream;
	/** C type : EdsUInt32 */
	public NativeLong reserved;
	public tagEdsSaveImageSetting() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("JPEGQuality", "iccProfileStream", "reserved");
	}
	/**
	 * @param JPEGQuality C type : EdsUInt32<br>
	 * @param iccProfileStream C type : EdsStreamRef<br>
	 * @param reserved C type : EdsUInt32
	 */
	public tagEdsSaveImageSetting(NativeLong JPEGQuality, EdsStreamRef iccProfileStream, NativeLong reserved) {
		super();
		this.JPEGQuality = JPEGQuality;
		this.iccProfileStream = iccProfileStream;
		this.reserved = reserved;
	}
	public tagEdsSaveImageSetting(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagEdsSaveImageSetting implements Structure.ByReference {
		
	};
	public static class ByValue extends tagEdsSaveImageSetting implements Structure.ByValue {
		
	};
}
